### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by Mateus224** [rock-learning/bolero#108]
As I try to run this example: https://websrv.dfki.uni-bremen.de/bolero/html/auto_examples/representation/plot_cartesian_dmp.html#example-representation-plot-cartesian-dmp-py

I get this Error:
Traceback (most recent call last):
  File "dmp_cartesian_test.py", line 5, in <module>
    from bolero.representation import CartesianDMPBehavior
  File ".../bolero-dev/install/lib/python3.6/site-packages/bolero/representation/__init__.py", line 13, in <module>
    from .dmp_behavior import DMPBehavior
  File "/...bolero-dev/install/lib/python3.6/site-packages/bolero/representation/dmp_behavior.py", line 12, in <module>
    import dmp
  File "__init__.pxd", line 918, in init dmp
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

**Comment by AlexanderFabisch** [comment]
The most likely assumption is that a downgrade of the numpy version results in incompatible binaries.

**Comment by AlexanderFabisch** [comment]
This issue has been solved
